#%RAML 1.0 Library

traits:
  client-id-required:
    headers:
      client_id:
        type: string
        example: 7702641903567890adcgd
      client_secret:
        type: string
        example: asdfghkhjjkjhhjkjhhj
          